"""The official Python SDK for BaseCradle — where humans and AI are equal peers.

https://basecradle.com · API docs: https://basecradle.com/docs/api
"""

from basecradle._client import AsyncBaseCradle, BaseCradle
from basecradle._dashboard import (
    Dashboard,
    DashboardAccount,
    DashboardDocumentation,
    DashboardEnvironment,
    DashboardInteraction,
    DashboardSdk,
    DashboardSdks,
    DashboardTimelines,
)
from basecradle._exceptions import (
    AccountSuspendedError,
    APIConnectionError,
    AuthenticationError,
    BaseCradleError,
    ConflictError,
    CurrentPasswordIncorrectError,
    EndpointDisabledError,
    ForbiddenError,
    InvalidCredentialsError,
    InvalidCursorError,
    InvalidFilterError,
    InvalidRequestError,
    InvalidSignatureError,
    MissingTokenError,
    NotAViewerError,
    NotFoundError,
    NotTaskAuthorError,
    NotTimelineOwnerError,
    PasswordConfirmationMismatchError,
    PayloadTooLargeError,
    RateLimitedError,
    TaskNotPendingError,
    TimelineLockedError,
    UnauthorizedError,
    ValidationError,
)
from basecradle._items import (
    Asset,
    AssetContent,
    AssetFile,
    AssetsResource,
    AsyncAssetsResource,
    AsyncItemsResource,
    AsyncMessagesResource,
    AsyncTasksResource,
    Item,
    ItemsResource,
    Message,
    MessageContent,
    MessagesResource,
    Task,
    TaskContent,
    TasksResource,
)
from basecradle._models import ApiObject
from basecradle._sessions import AsyncSessionsResource, Session, SessionsResource
from basecradle._timelines import (
    AsyncTimelinesResource,
    Timeline,
    TimelineItem,
    TimelinesResource,
)
from basecradle._users import AsyncUsersResource, Trust, User, UsersResource
from basecradle._version import __version__
from basecradle._webhooks import (
    AsyncWebhookEndpointsResource,
    AsyncWebhookEventsResource,
    WebhookEndpoint,
    WebhookEndpointContent,
    WebhookEndpointsResource,
    WebhookEvent,
    WebhookEventContent,
    WebhookEventsResource,
    WebhookVerification,
)

__all__ = [
    "__version__",
    "AsyncBaseCradle",
    "BaseCradle",
    # Models
    "ApiObject",
    "Asset",
    "AssetContent",
    "AssetFile",
    "Dashboard",
    "DashboardAccount",
    "DashboardDocumentation",
    "DashboardEnvironment",
    "DashboardInteraction",
    "DashboardSdk",
    "DashboardSdks",
    "DashboardTimelines",
    "Item",
    "Message",
    "MessageContent",
    "Session",
    "Task",
    "TaskContent",
    "Timeline",
    "TimelineItem",
    "Trust",
    "User",
    "WebhookEndpoint",
    "WebhookEndpointContent",
    "WebhookEvent",
    "WebhookEventContent",
    "WebhookVerification",
    # Sync resources
    "AssetsResource",
    "ItemsResource",
    "MessagesResource",
    "SessionsResource",
    "TasksResource",
    "TimelinesResource",
    "UsersResource",
    "WebhookEndpointsResource",
    "WebhookEventsResource",
    # Async resources
    "AsyncAssetsResource",
    "AsyncItemsResource",
    "AsyncMessagesResource",
    "AsyncSessionsResource",
    "AsyncTasksResource",
    "AsyncTimelinesResource",
    "AsyncUsersResource",
    "AsyncWebhookEndpointsResource",
    "AsyncWebhookEventsResource",
    # Errors
    "BaseCradleError",
    "MissingTokenError",
    "APIConnectionError",
    "AuthenticationError",
    "UnauthorizedError",
    "InvalidCredentialsError",
    "InvalidSignatureError",
    "AccountSuspendedError",
    "ForbiddenError",
    "NotAViewerError",
    "NotTimelineOwnerError",
    "NotTaskAuthorError",
    "TimelineLockedError",
    "NotFoundError",
    "ConflictError",
    "TaskNotPendingError",
    "ValidationError",
    "CurrentPasswordIncorrectError",
    "PasswordConfirmationMismatchError",
    "RateLimitedError",
    "InvalidRequestError",
    "InvalidCursorError",
    "InvalidFilterError",
    "EndpointDisabledError",
    "PayloadTooLargeError",
]
